# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b453b92dfd12dac608ff9d76a4aa2a2cdbe7d17e15f793fb13579cff996465f63d08bf6505e2f8d7c604016678b47005e7f51aeda3f247c2216140a57bfbe9e

test:
  secret_key_base: 2f5fd1a1ccc19bc17f1011227c3967ce35f8065bb7f95f5613154813dc3a2188fc4690dc1e4053cb1c2a02e8c24a9f1b1228d32ccfc277663ebffa5618f638cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
